### ISSUE TITLE
Homely - dotfile management

### ISSUE THREAD

**Issue by phodge** [BrisPy/talks#1]
Hi! I created a dotfile management tool in python that I'm happy to give a talk on: http://homely.readthedocs.io/

**Comment by romanofski** [comment]
Great! Would you mind letting me know:

* When to talk (March?)
* Length of the talk? (Maybe the topic suits for a lightning talk, but I can imagine a longer talk is fine too)

If you think you have material for a longer talk, would you mind posting a short abstract?

**Comment by phodge** [comment]
* March should be fine. Can you tell me what would be the exact date of the March meetup?
* I'd need 20 minutes or so to cover the project properly, and maybe allow some time for Q&A afterwards.
* I'll come back here and add a short abstract soon

**Comment by romanofski** [comment]
March meetup would be 1st Wednesday in the month which I think is the 1st of March. Looking forward to the abstract :)

**Comment by phodge** [comment]
Abstract
---

One of the joys of being a software developer is meticulously customising the various tools you use such that you maximumise their utility and potential for your own personal needs. These customisations are typically stored in files with names that begin with a dot (”.”), so developers have creatively named them “Dotfiles”.

One of the great frustrations as a software developer is jumping onto a different computer and having none of your customisations available. Many developers have taken to storing their Dotfiles in a git repository so that changes can be shared across computers easily, and then added shell scripts to automate their installation. However, the lack of programming features available in shell scripts soon becomes a dreadful burden as you continue to add more and more customisations to your shell script.

**homely** is a small tool which allows you to take a repository full of Dotfiles and script their installation using a real programming language (Python). It provides a small library containing the sorts of functions you need to programmatically write Dotfiles and install software packages, and a simple CLI tool to make running your installation script easy.
