### ISSUE TITLE
Finding more organisers specifically focused on talk selection?

### ISSUE THREAD

**Issue by ncoghlan** [BrisPy/talks#14]
The current BrisPy organisers are effectively me, @romanofski and @danc86, and we're nominally handling both talk selection *and* the venue logistics at the Red Hat office.

Would it make sense to try to recruit some folks specifically interested in finding local (or visting!) speakers each month, and split that responsibility out from the venue logistics?

**Comment by romanofski** [comment]
Hm... I feel like organising the event in the office is the trickier part than selecting the talks. So I'd be more interested to get more people to host the event if that is possible.

**Comment by ncoghlan** [comment]
Cycling through venues other than Red Hat would also be a possibility, but potentially makes things more difficult for attendees - there's a lot of value in having a consistent location every month.

However, there's even still potential benefits on that front in splitting the two sets of responsibilities withou bringing other venues into the mix - it means we can ask other Red Hatters to help with venue access, without also asking them to help with selecting talks or running the meetup.

So perhaps rather than starting with new volunteers, perhaps the first thing to do would be to write down a checklist of what needs to be done every month?

- choose topics/find speakers
- choose day (default: ???)
- find venue (default: Red Hat level 3)
- announce on MeetUp (organisers: see MeetUp group listing)
- order food (default: Red Hat sponsored pizza)
- put up signs at venue
- set up room
- welcome attendees
- introduce speakers
- provide food to attendees
- restore room to original state

**Comment by danc86** [comment]
> * order food

This is probably the most painful part. We don't get given budget by default, we have to beg for it each time. Last time @romanofski had to put together a blog post with some photos to justify the budget request.

A few weeks ago did receive a message to the Meetup organisers from a representative of Microsoft offering to supply food so maybe we should take them up on that.

**Comment by ncoghlan** [comment]
If MS are willing to contribute that way, +1 from me.

**Comment by romanofski** [comment]
Moving forward on this, what else is there to keep this open tho? Happy to write down a small document illustrating what needs to happen internally to prepare for the BrisPy meeting. Dan seems to get in contact with MS for catering. For talks, I've always thought asked for abstracts from proposals. That way it's a little commitment from the speaker to give the talk and for us useful in the announcements.

**Comment by ncoghlan** [comment]
@romanofski If you think my list above sounds reasonable, transferring that into the repository's README would probably make sense.

**Comment by cjrh** [comment]
I've previously asked management at Console Connect whether they would be open to hosting a Python meetup at our offices at 200 Mary Street in the CBD.  The response was "yes in principle", so I'll follow up on that and see if I can get a specific confirmation.

**Comment by ncoghlan** [comment]
This issue was moved to BrisPy/brispy-admin#3
