### ISSUE TITLE
Planning: July meetup

### ISSUE THREAD

**Issue by ncoghlan** [BrisPy/talks#15]
OK, we've missed the last few months, but I'd like to organise a couple of "PyCon Australia preview" talks for July, with folks speaking at PyCon Australia in August presenting draft versions of their talks.

**Comment by ncoghlan** [comment]
Tagging folks that participated in the discussion on #14: @danc86, @romanofski, @cjrh

TODO items:

- [x] choose day: Wed July 5th? (first Wednesday)
- [x] choose venue (default: Red Hat level 3. @cjrh, would the potential Console Connect venue have more space than RH, similar or less?)
- [x] announce on MeetUp (myself, @danc86 or @romanofski can do that once we're happy with the date & venue)
- [x] choose topics/find speakers (@ncoghlan - see below)
- [x] arrange food sponsorship (@danc86 - could you follow up with the MS contact you mentioned in #14?)

While the full program for PyCon AU hasn't been announced yet, it *has* been selected (I'm part of the review committee as one of the Education Seminar co-organisers), and speakers have been informed of their talk acceptance.

We have quite a few folks from Brisbane presenting, so I'll handle finding at least 2 of them willing to give a sneak peek at their presentations. I'll also arrange to let as many of them as I can know about this event, so they can potentially come say "Hi" to other attendees in a smaller local setting before heading down to Melbourne in August (We/I may also organise for local speakers to give re-runs of their PyCon AU talks at future meetups if that seems appropriate)

**Comment by danc86** [comment]
I replied to the Microsoft person who had reached out to us, and asked if the offer for food sponsorship still stands.

Btw I don't have any special backchannels, the message was just sent to all organizers on Meetup.com so I think @ncoghlan and @romanofski (and all the other old organizers) should be able to see and reply.

**Comment by cjrh** [comment]
At the moment, RH has the bigger space, but I'll find out if we can use the facilities on the mezzanine level in our building.  It's unlikely but I'll check and reply back here.   As for speakers, I have two colleagues willing to give short talks too.  One of them submitted to pycon AU and is on the waiting list.

**Comment by ncoghlan** [comment]
I've submitted the room access request for RH, once that's confirmed I'll update Meetup (even if I don't have confirmations back from speakers yet)

**Comment by ncoghlan** [comment]
OK, Meetup has been updated: https://www.meetup.com/Brisbane-Python-User-Group/events/240903163/

**Comment by ncoghlan** [comment]
Both invited speakers have confirmed their willingness and availability to present, so we'll have the following talks being presented:

- Tom Manderson speaking on Gradual Typing
- Emily de la Pena (founder of the Brisbane-based Coding Kids) speaking about teaching programming to primary school kids as part of the Digital Technologies curriculum

**Comment by danc86** [comment]
:tada: nice!

I will write back to our MSFT contact to say that our date is locked in and give them the agenda, and hopefully they will be able to order us some Subway for the meeting.

**Comment by danc86** [comment]
Seems like the MSFT catering offer has fallen through this time around...

**Comment by ncoghlan** [comment]
And a further follow-up: it was specifically ordering Subway that fell through. MSFT are still happy to sponsor pizza, we just need to get them the specifics of the order.

We should also be explicit regarding our desired delivery time (6:15 rather than 6:30)

**Comment by danc86** [comment]
Oh yeah, 6.30 is too late... I forgot that we had bumped up the start time to 5.45.

**Comment by ncoghlan** [comment]
The PyCon AU talk list is out now: https://pycon-au.org/schedule/list/
So I've updated the meetup listing with our preview speaker details: https://www.meetup.com/Brisbane-Python-User-Group/events/240903163/

With food sorted, I think that's everything except setting up the room and putting up signs on the night (including directing folks to Level 1 rather than Level 3).

**Comment by ncoghlan** [comment]
This issue was moved to BrisPy/brispy-admin#2
