### ISSUE TITLE
PyCon Australia 2017: local speakers

### ISSUE THREAD

**Issue by ncoghlan** [BrisPy/talks#18]
This is a collection of links for local speakers that are presenting at PyCon Australia 2017, so we can consider them as possible "preview" talks ahead of the conference, or "locale reprise" talks afterwards.

July 5th (first Wednesday) preview speakers:

- Emily de la Pena: [Python in Primary School](https://2017.pycon-au.org/schedule/presentation/63/)
- Tom Manderson: [Gradual Typing](https://2017.pycon-au.org/schedule/presentation/23/)

August 9th (2nd Wednesday due to scheduling conflict with PyCon AU) reprise speakers:

- Nick Coghlan: [Frontend integration testing with splinter](https://2017.pycon-au.org/schedule/presentation/42/)
- Charelle Collett: [Improving Your Documentation](https://2017.pycon-au.org/schedule/presentation/10/)

September reprise speakers:

- Anna Gerber: [IoT development with MicroPython](https://pycon-au.org/schedule/presentation/93/)
- Fraser Tweedale: [Social & Federated Authentication](https://2017.pycon-au.org/schedule/presentation/37/) (Caveat: may become unavailable if he ends up going to https://www.redhat.com/en/about/events/rhte-apac )

Other local presenters:

- Jim Lloyd: [Python in Senior IT](https://2017.pycon-au.org/schedule/presentation/78/)
- Clinton Roy: [State Machines](https://2017.pycon-au.org/schedule/presentation/33/) (unavailable August 2nd)

Let me know in the comments below if I missed anyone :)

**Comment by cjrh** [comment]
Anna Gerber - [Program all the things - How to develop IoT devices using MicroPython](https://pycon-au.org/schedule/presentation/93/). I've asked if she'd be willing to present at brispy on August 2nd.

**Comment by AnnaGerber** [comment]
I've got a lot on that week so I won't be able to make it on the 2nd but be happy to reprise my talk in September

**Comment by ncoghlan** [comment]
It turned out pretty much all the potential speakers (including me!) actually had schedule conflicts for August 2nd, so I've changed the date to August 9th, which allowed me to go back to the original plan of my Splinter talk and @Charcol's documentation one.

I've also added Anna as a speaker for September, and I think either Clinton's or Fraser's talk would pair well with that.

**Comment by ncoghlan** [comment]
We've worked through the 2017 local presenters, so closing this one :)
