### ISSUE TITLE
Getting into the CPython code base

### ISSUE THREAD

**Issue by elusivenode** [BrisPy/talks#19]
Would it be possible to do a talk on the best way to get started in contributing to CPython code base. I'm a medium term python user (3+ years) who aspires to contribute to the development process and, over the long run, become a core developer. I'm personally interested in the low level C implementation and issues like speed, the Gilectomy, C extensions and but there's a lot to digest when thinking about how to contribute.

When following bugs on the issue tracker and I find myself stuck with the best way to dig into the code base and get started in reproducing issues and thinking about potential patches. I think a talk about the general implementation of the CPython project and suggested places to dig into the code base would be interesting. Perhaps framed from the angle of an issue the was raised, reproduced and patched?

I'd be happy to have a go at putting something together from the a naive perspective. Would perhaps spark the interest of other attendees in this regard.

Cheers

Hamish

**Comment by danc86** [comment]
@ncoghlan is going to present on this topic for us at the November meeting, just announced.

🎉

**Comment by danc86** [comment]
Nick give a great presentation about this in November.
