### ISSUE TITLE
Getting started with Python

### ISSUE THREAD

**Issue by cjrh** [BrisPy/talks#24]
This proposal is a talk aimed at very new beginners (or those new to Python) who are just starting out and would like to know "how to begin".

I am putting my hand up to give this talk.

**Comment by KieranTHE** [comment]
Could also give this one if needed. Also know one or two people I would drag along if includes installing and setting up your basic environment.

**Comment by cjrh** [comment]
@KieranTHE Do you want to give this talk on 10/07/2019?

**Comment by KieranTHE** [comment]
@cjrh Happy to give this talk on 10/07/2019 if a speaker is needed. Will send a draft presentation to you Thursday evening same as last time. Does that work for you?

**Comment by cjrh** [comment]
Yeah sounds great! Thanks!  I'll add you to the roster.

**Comment by KieranTHE** [comment]
Link and upload for slides from last night's talk in case anyone comes looking here. https://1drv.ms/f/s!AiwwNx4TCjLCjOQ0VRASoiDFDYj0Ng 
[BrisPy-GettingStartedPython.pdf](https://github.com/BrisPy/talks/files/3380049/BrisPy-GettingStartedPython.pdf)
[BrisPy-GettingStartedPython.pptx](https://github.com/BrisPy/talks/files/3380050/BrisPy-GettingStartedPython.pptx)

**Comment by cjrh** [comment]
Thx @KieranTHE !
