### ISSUE TITLE
Testing with pytest

### ISSUE THREAD

**Issue by cjrh** [BrisPy/talks#28]
This could be a really great talk. I definitely heard @ashwini-balnaves voluteer to give this talk, so not adding the "speaker wanted" tag yet.

**Comment by rstuart85** [comment]
@ashwini-balnaves will be giving this talk in April.

**Comment by ashwini-balnaves** [comment]
Here are my slides 
[pytest pdfable.pdf](https://github.com/BrisPy/talks/files/3066674/pytest.pdfable.pdf)

**Comment by cjrh** [comment]
Your talk was great :100:

**Comment by melbit-tomcuddihy** [comment]
Hi @ashwini-balnaves,
This talk was indeed excellent. I went straight home and used your concept of defined contracts and parameterized testing to help me solve a problem I was struggling with at work.
THANK YOU!
