### ISSUE TITLE
Cython or writing C extensions in general

### ISSUE THREAD

**Issue by FlxVctr** [BrisPy/talks#3]
Unfortunately I'm not yet able to give a talk about this but would be very interested in the topic.

**Comment by romanofski** [comment]
Great idea 👍

**Comment by ncoghlan** [comment]
Perhaps @cjrh would be willing to give an updated edition of his Cython talk from PyCon AU 2015?

**Comment by cjrh** [comment]
Yep, I'd be happy to!

**Comment by elusivenode** [comment]
I'd be very interested in this topic

**Comment by rstuart85** [comment]
@cjrh Seems like a good idea for a talk? And I assume you already have something prepared?

**Comment by cjrh** [comment]
I can put a few slides together pretty quickly, sure.

**Comment by cjrh** [comment]
I am happy to give this talk, so removing the "speaker wanted" label and replacing with a "needs scheduling" label.

**Comment by cjrh** [comment]
This talk was given on March 13 2019 at RCL.

**Comment by FlxVctr** [comment]
@cjrh any chance you could post slides somewhere (if there are any)? I am not in Brisbane anymore, so I missed this talk.

**Comment by cjrh** [comment]
@FlxVctr I will try to make PDFs of the slides (I used reveal.js). But the slides might not be that useful on their own, as I spoke a lot to complement the content on the slides themselves. I'll see what I can do.
