### ISSUE TITLE
Getting started with logging

### ISSUE THREAD

**Issue by cjrh** [BrisPy/talks#30]

**Comment by ErinKenna** [comment]
I can do a logging talk this year. Tentatively for August? I'll be away until mid-June and can confirm once I'm back.

**Comment by cjrh** [comment]
@ErinKenna That would be excellent 👍 

Should I add you in now for 14/08, or would you prefer I wait until you can confirm a date?

**Comment by ErinKenna** [comment]
Sure @cjrh.  Lock it in and I'll figure it out in August.

**Comment by cjrh** [comment]
FYI @ErinKenna The date for this changed to **13/08/2019** because the 14th is a public holiday in QLD

**Comment by kaiw** [comment]
Sorry for the extremely late notice @ErinKenna but as you've probably seen, we've cancelled the August meetup for various reasons.

Is there any chance we could reschedule you for 11/09/2019?

**Comment by ErinKenna** [comment]
No problem @kaiw. Already spoke to Ryan and happy to reschedule.

**Comment by ErinKenna** [comment]
Talk material here: https://github.com/ErinKenna/loggingdemo.git 
Includes some notes on setting up the `conda` environment.
I'll try and add some unix notes as well later.
Feel free to fork, or request more examples.

**Comment by kaiw** [comment]
Thanks @ErinKenna!
