### ISSUE TITLE
Introduction to asyncio

### ISSUE THREAD

**Issue by cjrh** [BrisPy/talks#32]
I am happy to give this talk, but if someone else wants to that's good too!  I'd also be good to do this talk with someone else.

**Comment by waith** [comment]
will be good to cover Asynchronous processing and Parallel processing.
things to be mindful of, etc.

**Comment by cjrh** [comment]
@kaiw @rstuart85 This has been open since March and there have been no volunteers, so I reckon I'm happy to do this in the new year.  But what I actually would like to do is something more like a hands-on workshop where attendees can follow along on their own laptops if they choose to.  I'm thinking of a length of time of around 45-60 minutes. I think I can do a pretty solid job in 60 minutes.

**Comment by kaiw** [comment]
Given that we've had people ask asyncio questions at meetups more than once, I think a workshop-style session would be great. We'll have to make it clear when we schedule the meetup that this is what we're aiming for, but that's fine.

My only suggestion would be that if you could figure out a natural split in the workshop at around 30 minutes then that would let us have the usual food break, and also might give a chance to help out anyone who falls behind.

Did you have a month in mind? if so I think we could lock it in now.

**Comment by cjrh** [comment]
Jan or Feb is fine by me.

**Comment by kaiw** [comment]
Let's say January then, which will be January 8. Is that okay?

**Comment by cjrh** [comment]
yeah I can do that

**Comment by kaiw** [comment]
Awesome, thanks!

**Comment by cjrh** [comment]
This one has been done!
