### ISSUE TITLE
Threading: when the GIL matters, and when it doesn't

### ISSUE THREAD

**Issue by cjrh** [BrisPy/talks#33]

**Comment by EpicWink** [comment]
Hi, it's Laurie. I'm happy talk about things GIL.

I know:
* why the GIL exists
* when/why the GIL is released in use of Python
* how it's manipulated in C extensions for Python
* ways to make the GIL not affect code
* all the ins and outs of `threading` and `multiprocessing` standard libraries
* how multi-threading and multi-processing works in C (on UNIX)

I only know about CPython: I'd have to research how it's different in other Python implementations. Also, I have little experience in `asyncio`, so there's more research and tinkering there

**Comment by cjrh** [comment]
@EpicWink Great!  I'll add you in for the meetup on 12 June.

I think a "when to use what and how" for threading & multiprocessing would be great, but by all means if there is something specific you want to say then go for it.  I think regarding asyncio it's fine for you to say "I don't have personal experience with this but from my research, here's xyz".

I have a lot of experience with asyncio, so if you like you can run your slides past me before the day and I can give them a scan to see if anything regarding asyncio is accurate?

**Comment by cjrh** [comment]
I'll make up a title for now, but when you have a better idea just let me know and I'll change the title on the roster.

**Comment by cjrh** [comment]
@EpicWink just checking in, you still ok to present next week?

**Comment by EpicWink** [comment]
@cjrh, yeah, no issues

**Comment by EpicWink** [comment]
@cjrh How do I provide my slides?

As a direct attachment? As PDF? Just a OneDrive link?

**Comment by cjrh** [comment]
PDF is fine. You can drop them in this issue. Thanks again for the talk!

**Comment by EpicWink** [comment]
Here it is: [threading-gil.pdf](https://github.com/BrisPy/talks/files/3286113/threading-gil.pdf)

More info:
* http://python-notes.curiousefficiency.org/en/latest/python3/multicore_python.html
