### ISSUE TITLE
A simple REST API using the Flask web framework

### ISSUE THREAD

**Issue by cjrh** [BrisPy/talks#34]
This should be a beginner-level talk that guides a beginner through the set up of a simple API project, considerations in designing the resultful API itself, and (hopefully if there is time) how to get it running on, e.g. an AWS compute instance.  It would be awesome for an attendee to leave with enough of an introduction to get their own API running somewhere in the cloud.

**Comment by phodge** [comment]
A tutorial on setting up a basic GraphQL API using Flask would also be great, I'm only hearing good things about it from web devs.

**Comment by cjrh** [comment]
@phodge Are you offering to be the speaker, or just +1ing the topic? 😊

**Comment by phodge** [comment]
haha, just +1ing the topic.

**Comment by c12k** [comment]
I'm happy to have a go presenting this one.

**Comment by cjrh** [comment]
Great @cmcc13! Can I schedule you for 12/06/2019?

**Comment by cjrh** [comment]
Scheduled for 12/06/2019.

**Comment by c12k** [comment]
There is a slim possibility I have to travel that week.  I'll let you know as early as I can if that is the case.  If so , I'm happy to do the following month.

**Comment by cjrh** [comment]
@cmcc13 Are you still ok to present next week?

**Comment by c12k** [comment]
Yes. I'm good to go.

**Comment by c12k** [comment]
Here's a link to the presentation:
https://docs.google.com/presentation/d/1_EYQG7vnZ1it93h2X80REfLTjgMAv1z9mcp4cw4sWZo/edit?usp=sharing
And the GitHub repo:
https://github.com/cmcc13/FlaskAPI

**Comment by cjrh** [comment]
Thanks for the talk!
