### ISSUE TITLE
Working with Dates and Times in Python

### ISSUE THREAD

**Issue by cjrh** [BrisPy/talks#40]

**Comment by ghost** [comment]
Hi guys, Kieran Thompson here. As discussed with Ryan and Caleb after the talks on Wednesday (13/03) I would be keen try and give the talk on Working with Dates and Times in Python. If the next meeting will be the 10/04, I'm available to give it then.

**Comment by cjrh** [comment]
@kieranh45 righto, I'll book you in!

**Comment by cjrh** [comment]
@kieranh45 your talk was great :100:
