### ISSUE TITLE
Build Command Line Interface (CLI) application with cmd2

### ISSUE THREAD

**Issue by ymkim92** [BrisPy/talks#42]
I can be a speaker with this topic if you accept this :-)

- Command vs CLI
- CLI vs GUI
- Simple CLI application based on cmd2
  - add commands
  - autocompletion
  - scripting
- Case study
  - testing device by cmd2 and ssh

**Comment by cjrh** [comment]
@ymkim92 Can I schedule you for 10 July?

**Comment by ymkim92** [comment]
@cjrh Yes I can

**Comment by cjrh** [comment]
Scheduled for 10 July 2019.

**Comment by ymkim92** [comment]
You can find my presentation and examples here:
https://github.com/ymkim92/python_cli
Thank you!

**Comment by cjrh** [comment]
Thanks @ymkim92 !
