### ISSUE TITLE
git for version control

### ISSUE THREAD

**Issue by ErinKenna** [BrisPy/talks#44]

**Comment by paulstockwell** [comment]
I'll put my hand up to do this one.

@cjrh do you have a beginner talk for 13/11/19 yet?

**Comment by cjrh** [comment]
If the README doesn't have the slot filled, then there's no talk yet. Shall I add you in for the 13th?

**Comment by paulstockwell** [comment]
Sure. Let's do it.  I'll get in touch to go over the content sometime soon.

**Comment by kaiw** [comment]
@paulstockwell I've just put you down for the beginner slot. Thanks! I've used a placeholder talk title for now, but I can update it easily enough if you have a title in mind.

**Comment by kaiw** [comment]
@paulstockwell Just checking that you're still good for next week. There's no need for anyone to go over your content (unless you want someone to!) but I wanted to make sure that we're still on track.

**Comment by paulstockwell** [comment]
Thanks Kai. Yep, I'm still good for next Wednesday.

**Comment by kaiw** [comment]
Thanks again!

**Comment by amparaj** [comment]
Hi Paul @paulstockwell
I was at the presentation and found it highly useful. Was wondering if you could share your slides you did as we are looking at using Gitlab at work for internal version control, it would assist explaining it to the rest of the team.

**Comment by dhirschfeld** [comment]
I agree - it was a very good intro/overview for git! :+1:

 In case a couple more resources are of interest the below are also both very good:
* https://speakerdeck.com/alicebartlett/git-for-humans
* https://bitbucket.org/blog/get-git-guru-gold-with-bitbuckets-glorious-git-guides

The former is a very clean, no-jargon intro targeted at non-developers whilst the latter is a whole set of tutorials which take you from the basics through to more advanced concepts
