### ISSUE TITLE
Introduction to numpy/pandas

### ISSUE THREAD

**Issue by kaiw** [BrisPy/talks#46]
This would most likely be a general slot talk aimed at introducing the audience to numpy & pandas packages, what they're used for, and a general demonstration of how to use them.

**Comment by kaiw** [comment]
Given that our usual slots are ~25 minutes, I'm not sure whether it makes sense to do both numpy & pandas, or whether it would be better to go into slightly more depth on just one of them.

@rancoxu Would you be interested in doing this at the next meetup on Wednesday, November 13?

**Comment by rancoxu** [comment]
i'm not sure, if going a bit deeper on numpy i might talk a bit about its application in image/sound processing? pandas is more plain i suppose, more basics to cover and 25 min sounds about right.

**Comment by rancoxu** [comment]
time's great! I'll leave Nov 13th blank for this session.

**Comment by kaiw** [comment]
> i'm not sure, if going a bit deeper on numpy i might talk a bit about its application in image/sound processing?

I think it's often good to have an application domain to provide motivation and examples, so sounds interesting to me!

> pandas is more plain i suppose, more basics to cover and 25 min sounds about right.

Agreed.

I think you could easily talk about either. Let me know which topic you'd prefer to present, and I'll lock it in.

**Comment by rancoxu** [comment]
haha cool numpy it is! I'll compose a tentative lecture script by tmrw and maybe have a bit of discussion with you, is that ok?

**Comment by kaiw** [comment]
Sounds good!

**Comment by rancoxu** [comment]
Hi Kai,
  How are you?
  So I have compiled a tentative tutorial script on numpy please have a
look at it. However, I usually spend 2 hours with my students on it.
  In that case, I think I might wanna go straight to audio and image
manipulation after briefly going over the numpy basics. If the feedback is
mostly positive, I will probably cover more basics in a later session?
All the best,
Ranco

**Comment by rancoxu** [comment]
Hi Kai,
  How are you?
  So I have compiled a tentative tutorial script on numpy please have a look at it. However, I usually spend 2 hours with my students on it.
  In that case, I think I might wanna go straight to audio and image manipulation after briefly going over the numpy basics. If the feedback is mostly positive, I will probably cover more basics in a later session?
All the best,
Ranco

**Comment by rancoxu** [comment]
import numpy as np
import os
import sounddevice as sd
import matplotlib.pyplot as plt
import cv2

# change cwd
os.chdir(os.path.dirname(os.path.realpath(__file__)))

# Basics
print('*' * 50, 'Basics', '*' * 50)
a = np.arange(10).reshape(2, 5)
print(a)

b = np.array([[1, 2, 3], [4, 5, 6]], dtype='int16')  # by default 'int32'
print(b)
print(b[0, :])

# Get dim
print('*' * 50, 'Get Dimension', '*' * 50)
print(a.ndim)

# Get shape
print('*' * 50, 'Get Shape', '*' * 50)
print(a.shape)

# Get memory
print('*' * 50, 'Unit memory size', '*' * 50)
print(a.itemsize)

# Total size
print('*' * 50, 'Total size', '*' * 50)
print(a.itemsize * a.size)
print(a.nbytes)

# Get type
print('*' * 50, 'Get data type', '*' * 50)
print(b.dtype)

# Access/change specific location
print('*' * 50, 'Access/change specific location', '*' * 50)
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

# Get a specific element
print(a[0, 1])
print(a[0, -2])

# Get a row/col
print('*' * 50, 'Get a row/col', '*' * 50)
print(a[1, :])
print(a[:, 0])

# [start:end:step] index
print('*' * 50, 'Indexing with steps', '*' * 50)
print(a[0, 0:-1:2])

# Initialization
print('*' * 50, 'Initialization', '*' * 50)
a = np.zeros((2, 3))
b = np.ones((3, 4))
c = np.eye(4)
d = np.identity(4)
print(a, '\n\n', b, '\n\n', c, '\n\n', d)

# Any number
print('*' * 50, 'Initialize any array', '*' * 50)
d = np.full((3, 3), 99)
print(d)
dd = np.full_like(a, 5)
print(dd)

# Random array
print('*' * 50, 'Random array', '*' * 50)
a = np.random.rand(3, 3)
print(a)
b = np.random.random_sample(a.shape)
print(b)
c = np.random.randint(1, 3, size=(2, 3))
print(c)

# Repeat array
print('*' * 50, 'Repeat array', '*' * 50)
a1 = np.repeat(3, 5)
print(a1)

x = np.array([[1, 2], [3, 4], [5, 6]])
print(x)
# By default, flatten out
a2 = np.repeat(x, 3)
print(a2)
# By row
a3 = np.repeat(x, 3, axis=0)
print(a3)

# By column
a4 = np.repeat(x, 3, axis=1)
print(a4)

# Uneven
a5 = np.repeat(x, [1, 2, 2], axis=0)
print(a5)

# Test: Initialize a matrix
print('*' * 50, 'Quiz', '*' * 50)
'''
[ 1 1 1 1 1
  1 0 0 0 1
  1 0 9 0 1
  1 0 0 0 1
  1 1 1 1 1  ]
'''
test = np.repeat(np.array([np.repeat(1, 5), [1, 0, 0, 0, 1], np.repeat(1, 5)]), [1, 3, 1], axis=0)
test[2, 2] = 9
print(test)

# Copy arrays is by reference
print('*' * 50, 'Copy by value/reference', '*' * 50)
a = np.array([1, 2, 3])
b = a
c = a.copy()
print(a)
print(b)
b[0] = 100
print(a)
print(c)

# Matrix Calcs
print('*' * 50, 'Array Calculations', '*' * 50)
a = np.array([1, 2, 3, 4])
print(a + 2)
print(a - 2)
print(a / 2)
print(a * 2)

# By default elementwise
b = np.array([1, -1, 1, -1])
print(a + b)
print(a ** 2)
print(np.sin(a))

# Linear algebra (Matlab)
# a*b=c
print('*' * 50, 'Matrix multiplication', '*' * 50)
a = np.array([[5, -6, -7], [6, -4, 10], [2, 4, -3]])
print(a)
b = np.array([[2, 4, -3]]).T
print(b)
# here make sure to use [[]] sp that transpose works with 2D array
c = np.array([[7, -34, 29]]).T
print(c)

# solve for c=a*b
print(f"matmul(a,b) returns\n{np.matmul(a, b)}")
print(f"a@b returns\n{a @ b}")
# slove for b=a\b
print(np.linalg.solve(a, c))
print(np.matmul(np.linalg.inv(a), c))

# Determinant
print('*' * 50, 'Linear Algebra', '*' * 50)
c = np.identity(3)  # should be 1
print(np.linalg.det(c))
print(np.linalg.eig(c))
print(np.linalg.inv(c))

# Statistics
print('*' * 50, 'Statistics', '*' * 50)
stats = np.array([[1, 2, 3], [4, 5, 6]])
# 0:by col / 1: by row
print(np.min(stats, axis=1))
print(np.sum(stats, axis=1))

# Reorganizing arrays
print('*' * 50, 'Re-organizing array', '*' * 50)
be4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(be4)
# size must match
after = be4.reshape((8, 1))
print(after)

# vertically stack vectors
print('*' * 50, 'Append array by row/col', '*' * 50)
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
print(np.vstack([v1, v2]))
print(np.vstack([v1, v2, v2]))

# Horizontal stack vectors
print(np.hstack([v1, v2]))

# Miscellaneous
print('*' * 50, 'Load in data', '*' * 50)
# Load data from file
rf = np.recfromcsv('data.csv', dtype='int32')
print(rf)

# Advanced index (boolean)
print('*' * 50, 'Advanced index technique-Boolean index', '*' * 50)
a = np.random.randint(100, size=(4, 6))
print(a)
print(a > 50)
print(a[a > 50])
print(np.any(a > 50, axis=0))
print(np.all(a > 50, axis=0))

# Multiple criteria
print('*' * 50, 'Multiple criteria', '*' * 50)
print((~((a > 50) & (a < 100))))

# diagonal matrix
print('*' * 50, 'Diagonal Matrix', '*' * 50)
test = np.arange(1, 31).reshape((6, 5))
print(test)
print(np.diag(test, 1))
print(np.diag([1, 2, 3, 4]))

# audio manipulation
print('*' * 50, 'Audio manipulation', '*' * 50)
# set parameters
sampling_time = 1
frequency = 44100
# generate x values that later on subbed into sin() to emulate sound wave
x = np.arange(0, sampling_time * frequency)
wave = np.sin(x)
sd.play(wave, samplerate=frequency, blocking=True)

# image manipulation
# random dots
print('*' * 50, 'Image manipulation', '*' * 50)
pixels_gray = np.random.randint(0, 255, (128, 128))
plt.imshow(pixels_gray, cmap='gray', vmin=0, vmax=255)
plt.grid(False)
plt.show()

# image fiddling
img=cv2.imread('pup.jpg')
# convert RGB to Grayscale
img_gray=cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)
print(img_gray.shape)
print(img_gray)
plt.imshow(img_gray,cmap='gray')
plt.show()

**Comment by kaiw** [comment]
> So I have compiled a tentative tutorial script on numpy please have a look at it. However, I usually spend 2 hours with my students on it.

Yeah, I can see that there's a lot of content here! I think for our audience, the challenge is that you'll need to introduce the extreme basics (i.e., what is numpy, what is a numpy array/matrix and how does it differ from a python list, etc.) and then give examples of why someone would use it.

> In that case, I think I might wanna go straight to audio and image manipulation after briefly going over the numpy basics. If the feedback is mostly positive, I will probably cover more basics in a later session?

I think I'd suggest not making this too much of an API tutorial, but rather focus more on explaining how to do/think about things with numpy, if that makes sense?

Are you thinking of presenting this as a series of jupyter notebooks demos?  The audio & image manipulation sounds like it would make a good motivating example.

**Comment by rancoxu** [comment]
ok no problem i'll simplify it and yes jupyter notebook will make it easier to display the result along explanation

**Comment by kaiw** [comment]
@rancoxu I've scheduled you in for the general slot but with a generic talk title (see https://github.com/BrisPy/talks). If you want to send me updated details that would be cool.

**Comment by rancoxu** [comment]
@kaiw Hi Kai, time's perfect for me. i'm a bit caught up in interviews and tutoring recently but i'll come up with a new script be4 Thur. is that ok?

**Comment by kaiw** [comment]
Yeah that's all good. You're welcome to send things through for feedback, but you also don't have to. I'm happy either way.

**Comment by rancoxu** [comment]
import numpy as np
import os
import sounddevice as sd
import matplotlib.pyplot as plt
import cv2

# change cwd
os.chdir(os.path.dirname(os.path.realpath(__file__)))

# Basics
print('*' * 50, 'Basics', '*' * 50)
a = np.arange(10).reshape(2, 5)
print(a)

b = np.array([[1, 2, 3], [4, 5, 6]], dtype='int16')  # by default 'int32'
print(b)
print(b[0, :])

# Get dim
print('*' * 50, 'Get Dimension', '*' * 50)
print(a.ndim)

# Get shape
print('*' * 50, 'Get Shape', '*' * 50)
print(a.shape)

# Access/change specific location
print('*' * 50, 'Access/change specific location', '*' * 50)
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

# Get a specific element
print(a[0, 1])
print(a[0, -2])

# Get a row/col
print('*' * 50, 'Get a row/col', '*' * 50)
print(a[1, :])
print(a[:, 0])

# [start:end:step] index
print('*' * 50, 'Indexing with steps', '*' * 50)
print(a[0, 0:-1:2])

# Initialization
print('*' * 50, 'Initialization', '*' * 50)
a = np.zeros((2, 3))
b = np.ones((3, 4))
c = np.eye(4)
d = np.identity(4)
print(a, '\n\n', b, '\n\n', c, '\n\n', d)


# Random array
print('*' * 50, 'Random array', '*' * 50)
a = np.random.rand(3, 3)
print(a)
b = np.random.random_sample(a.shape)
print(b)
c = np.random.randint(1, 3, size=(2, 3))
print(c)


# Matrix Calcs
print('*' * 50, 'Array Calculations', '*' * 50)
a = np.array([1, 2, 3, 4])
print(a + 2)
print(a - 2)
print(a / 2)
print(a * 2)

# By default elementwise
b = np.array([1, -1, 1, -1])
print(a + b)
print(a ** 2)
print(np.sin(a))

# Reorganizing arrays
print('*' * 50, 'Re-organizing array', '*' * 50)
be4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(be4)
# size must match
after = be4.reshape((8, 1))
print(after)

# audio manipulation
print('*' * 50, 'Audio manipulation', '*' * 50)
# set parameters
sampling_time = 1
frequency = 44100
# generate x values that later on subbed into sin() to emulate sound wave
x = np.arange(0, sampling_time * frequency)
wave = np.sin(x)
sd.play(wave, samplerate=frequency, blocking=True)

# image manipulation
# random dots
print('*' * 50, 'Image manipulation', '*' * 50)
pixels_gray = np.random.randint(0, 255, (128, 128))
plt.imshow(pixels_gray, cmap='gray', vmin=0, vmax=255)
plt.grid(False)
plt.show()

# image fiddling
img=cv2.imread('pup.jpg')
# convert RGB to Grayscale
img_gray=cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)
print(img_gray.shape)
print(img_gray)
plt.imshow(img_gray,cmap='gray')
plt.show()

**Comment by rancoxu** [comment]
> Yeah that's all good. You're welcome to send things through for feedback, but you also don't have to. I'm happy either way.

Hi Kai, can you please have a look at this simplified version and let me know if there's anything that needs to change? Thx a lot.
Ranco

**Comment by kaiw** [comment]
Looks good to me! Honestly, it's also pretty hard to judge a presentation from a workbook.

I think my main comment here would be that I think it's easy when doing a notebook-based presentation to go through the content very quickly, just because you already know it well, and there's an assumption that people can follow the on-screen code fairly easily. If you're already planning to talk through the lines here a bit (e.g., in the Basics section I assume you'll talk through the data types aspect of numpy arrays) then I think this seems good!

**Comment by rancoxu** [comment]
Alright! I'll add that in when doing presentation!
Thanks for ur advice.
Best wishes,
Ranco

**Comment by rancoxu** [comment]
@kaiw Kai just wondering what time would this session be?

**Comment by kaiw** [comment]
It's scheduled for 6:50pm, since you'd be the general track talk (the
beginner talk goes first). See
https://www.meetup.com/Brisbane-Python-User-Group/events/265543641/

Is that okay for you?

**Comment by rancoxu** [comment]
Yes that's perfect for me!

**Comment by rancoxu** [comment]
@kaiw hi Kai, i might be late for  about 30min today as i get off work at 6pm and usually it takes about 15min to go to river lab. Plz lemme know if there's anything i can do beforehand and sorry for the inconvenience.

**Comment by kaiw** [comment]
@rancoxu Don't worry about it, that'll be fine! The break for snacks and socialising is usually about 6:30, so come find one of the organisers when you arrive (we'll probably be obvious, but if I can't find you I'll wait up the front). If you're slightly late, that's okay too... we'll just let people chat for a bit longer during the break.

**Comment by rancoxu** [comment]
sounds great!

**Comment by kaiw** [comment]
Thanks for doing this!
