### ISSUE TITLE
Caterpillar: a library for text analytics

### ISSUE THREAD

**Issue by SamHames** [BrisPy/talks#6]
I spend a lot of time working on this library:

https://github.com/kapiche/caterpillar

It integrates full text indexing with some extra features for text analytics - we're aiming for it to be a bridge between search/topic modelling/NLP and machine learning approaches to text.

(Also gives might be just the nudge I need to clean up a bunch of things and make a 1.0 release...)

**Comment by danc86** [comment]
Hey Sam! I know it's super short notice but would you be willing to talk about this library at a meeting next Wednesday (11 Oct)?

**Comment by SamHames** [comment]
I don't have anything prepared, so a bit short notice for me unfortunately.

I'd be more than happy to do this in the next couple of months though.

**Comment by danc86** [comment]
Okay no worries. :-) Would you consider it for 8 November instead?

**Comment by SamHames** [comment]
Yes - happy to lock it in now.

**Comment by danc86** [comment]
Sam gave a great presentation about this back in November.
